steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'APP_ENV',
        '--build-arg',
        'CORS_ORIGIN',
        '--build-arg',
        'DB_HOST',
        '--build-arg',
        'DB_PORT',
        '--build-arg',
        'DB_USERNAME',
        '--build-arg',
        'DB_PASSWORD',
        '--build-arg',
        'DB_DATABASE',
        '--build-arg',
        'TIMESCALE_DB_HOST',
        '--build-arg',
        'TIMESCALE_DB_PORT',
        '--build-arg',
        'TIMESCALE_DB_USERNAME',
        '--build-arg',
        'TIMESCALE_DB_PASSWORD',
        '--build-arg',
        'TIMESCALE_DB_DATABASE',
        '-t',
        'gcr.io/${PROJECT_ID}/x1000-server-staging:$SHORT_SHA',
        '.',
      ]
    secretEnv:
      [
        'APP_ENV',
        'CORS_ORIGIN',
        'DB_HOST',
        'DB_PORT',
        'DB_USERNAME',
        'DB_PASSWORD',
        'DB_DATABASE',
        'TIMESCALE_DB_HOST',
        'TIMESCALE_DB_PORT',
        'TIMESCALE_DB_USERNAME',
        'TIMESCALE_DB_PASSWORD',
        'TIMESCALE_DB_DATABASE',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/x1000-server-staging:$SHORT_SHA']
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "x1000-server-staging"
      - "--image"
      - "gcr.io/${PROJECT_ID}/x1000-server-staging:$SHORT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--vpc-connector"
      - "queue-connector"
      - "--allow-unauthenticated"
      - "--min-instances"
      - "1"
      - "--max-instances"
      - "1"

timeout: 1200s

images:
  - gcr.io/${PROJECT_ID}/x1000-server-staging:$SHORT_SHA
options:
  machineType: "E2_HIGHCPU_8"

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/X1000_SERVER_STAG_APP_ENV/versions/latest
      env: APP_ENV
    - versionName: projects/${PROJECT_ID}/secrets/X1000_SERVER_STAG_CORS_ORIGIN/versions/latest
      env: CORS_ORIGIN
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_HOST/versions/latest
      env: DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_PORT/versions/latest
      env: DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_USERNAME/versions/latest
      env: DB_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/X1000_SERVER_STAG_DB_DATABASE/versions/latest
      env: DB_DATABASE
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_HOST/versions/latest
      env: TIMESCALE_DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_PORT/versions/latest
      env: TIMESCALE_DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_USERNAME/versions/latest
      env: TIMESCALE_DB_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_PASSWORD/versions/latest
      env: TIMESCALE_DB_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_DATABASE/versions/latest
      env: TIMESCALE_DB_DATABASE