steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'APP_ENV',
        '--build-arg',
        'CORS_ORIGIN',
        '--build-arg',
        'DB_HOST',
        '--build-arg',
        'DB_PORT',
        '--build-arg',
        'DB_USERNAME',
        '--build-arg',
        'DB_PASSWORD',
        '--build-arg',
        'DB_DATABASE',
        '--build-arg',
        'TIMESCALE_DB_HOST',
        '--build-arg',
        'TIMESCALE_DB_PORT',
        '--build-arg',
        'TIMESCALE_DB_USERNAME',
        '--build-arg',
        'TIMESCALE_DB_PASSWORD',
        '--build-arg',
        'TIMESCALE_DB_DATABASE',
        '-f',
        'vm.Dockerfile',
        '-t',
        'gcr.io/${PROJECT_ID}/x1000-vm-stag:$SHORT_SHA',
        '.',
      ]
    secretEnv:
      [
        'APP_ENV',
        'CORS_ORIGIN',
        'DB_HOST',
        'DB_PORT',
        'DB_USERNAME',
        'DB_PASSWORD',
        'DB_DATABASE',
        'TIMESCALE_DB_HOST',
        'TIMESCALE_DB_PORT',
        'TIMESCALE_DB_USERNAME',
        'TIMESCALE_DB_PASSWORD',
        'TIMESCALE_DB_DATABASE',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/x1000-vm-stag:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    id: create-instance-template
    args:
      - compute
      - instance-templates
      - create-with-container
      - x1000-vm-stag-t-v1-$_ENV-$BUILD_ID
      - --custom-cpu=1
      - --custom-memory=4GB
      - --boot-disk-size=20GB
      - --region=asia-northeast1
      - --subnet=default
      - --tags=allow-hc-and-proxy,allow-ssh,allow-http,allow-https,allow-5432-tcp
      - --container-image
      - gcr.io/${PROJECT_ID}/x1000-vm-stag:$SHORT_SHA
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [
      '-c',
      'gcloud compute instance-groups managed rolling-action
        start-update x1000-vm-stag-mig
        --version=template=x1000-vm-stag-t-v1-$_ENV-$BUILD_ID
        --region=asia-northeast1 --max-unavailable=0',
    ]

availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/X1000_SERVER_STAG_APP_ENV/versions/latest
      env: APP_ENV
    - versionName: projects/${PROJECT_ID}/secrets/X1000_SERVER_STAG_CORS_ORIGIN/versions/latest
      env: CORS_ORIGIN
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_HOST/versions/latest
      env: DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_PORT/versions/latest
      env: DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_USERNAME/versions/latest
      env: DB_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/LOOTBOT_SECURITY_BOX_DB_PASSWORD/versions/latest
      env: DB_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/X1000_SERVER_STAG_DB_DATABASE/versions/latest
      env: DB_DATABASE
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_HOST/versions/latest
      env: TIMESCALE_DB_HOST
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_PORT/versions/latest
      env: TIMESCALE_DB_PORT
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_USERNAME/versions/latest
      env: TIMESCALE_DB_USERNAME
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_PASSWORD/versions/latest
      env: TIMESCALE_DB_PASSWORD
    - versionName: projects/${PROJECT_ID}/secrets/X1000_STAG_TIMESCALE_DB_DATABASE/versions/latest
      env: TIMESCALE_DB_DATABASE