version: '3.8'
services:
  app:
    image: tma-server:1.0.0-dev
    container_name: tma-server-dev
    build:
      context: .
      dockerfile: docker/nest/dev.dockerfile
    working_dir: /home/node/workspace
    command: npm run start:debug
    restart: unless-stopped
    tty: true
    volumes:
      - .:/home/node/workspace
      - /home/node/workspace/node_modules
    networks:
      - tma-network
    env_file:
      - .env.dev
    ports:
      - '8003:8003'

  redis:
    container_name: tma-redis
    image: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - tma-network
    volumes:
      - tma-redis:/data

  database:
    container_name: tma-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - tma-database:/var/lib/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - tma-network

networks:
  tma-network:
    driver: bridge

volumes:
  tma-redis:
    driver: local
  tma-database:
    driver: local
