version: "3.8"
services:
  app:
    image: x1000-server:1.0.0-dev
    container_name: x1000-server-dev
    build:
      context: .
      dockerfile: docker/nest/dev.dockerfile
    working_dir: /home/node/workspace
    command: npm run start:debug
    restart: unless-stopped
    tty: true
    volumes:
      - .:/home/node/workspace
      - /home/node/workspace/node_modules
    networks:
      -  x1000-network
    env_file:
      - .env.dev
    ports:
      - '8003:8003'

  redis:
    container_name: x1000-redis
    image: redis
    restart: unless-stopped
    ports:
      - 6380:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - x1000-network
    volumes:
      - x1000-redis:/data

  database:
    container_name: x1000-database
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - x1000-database:/var/lib/postgres
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    networks:
      - x1000-network

networks:
  x1000-network:
    driver: bridge

volumes:
  x1000-redis:
    driver: local
  x1000-database:
    driver: local